import { isDone, phaseLabel, phaseStatus, subPhaseLabel, type Phase, type Roadmap, type SubPhase } from './model.ts';

const BAR_WIDTH = 24;

export function render(roadmap: Roadmap): string {
  const allSubPhases = roadmap.phases.flatMap((p) => p.subPhases);
  const doneCount = allSubPhases.filter((s) => s.status === 'done').length;
  const phasesDone = roadmap.phases.filter((p) => phaseStatus(p) === 'done').length;
  const lines: string[] = [];

  lines.push('# ERP-AI-Pro Roadmap');
  lines.push('');
  lines.push('<!-- Generated by `node scripts/roadmap/roadmap.ts build` from roadmap.json. Do not edit by hand. -->');
  lines.push('');
  lines.push(
    `Updated ${roadmap.updatedOn} · Sub-phases done: ${doneCount}/${allSubPhases.length} · Phases done: ${phasesDone}/${roadmap.phases.length}`,
  );
  lines.push('');
  lines.push(`\`${progressBar(doneCount, allSubPhases.length)}\``);
  lines.push('');
  lines.push('Legend: `[x]` done · `[ ]` planned · `⏳` in progress · `⛔` blocked · `⏸` deferred');
  lines.push('');

  lines.push('## Milestones');
  lines.push('');
  lines.push('| Milestone | Phases | Progress |');
  lines.push('|---|---|---|');
  for (const milestone of roadmap.milestones) {
    const phases = roadmap.phases
      .map((p, i) => ({ p, i }))
      .filter(({ p }) => p.milestone === milestone.id);
    const subs = phases.flatMap(({ p }) => p.subPhases);
    const done = subs.filter((s) => s.status === 'done').length;
    const labels = phases.map(({ i }) => phaseLabel(i)).join(', ') || '—';
    lines.push(`| **${milestone.title}** — ${milestone.description} | ${labels} | ${done}/${subs.length} |`);
  }
  lines.push('');

  lines.push('## Phases');
  lines.push('');
  lines.push('| Label | Phase | Milestone | Status | Done |');
  lines.push('|---|---|---|---|---|');
  for (const [index, phase] of roadmap.phases.entries()) {
    const done = phase.subPhases.filter((s) => s.status === 'done').length;
    const milestone = roadmap.milestones.find((m) => m.id === phase.milestone)?.title ?? phase.milestone;
    lines.push(
      `| ${phaseLabel(index)} | [${phase.title}](#phase-${phase.id}) | ${milestone} | ${statusText(phaseStatus(phase))} | ${done}/${phase.subPhases.length} |`,
    );
  }
  lines.push('');

  lines.push('## Next up');
  lines.push('');
  for (const [phaseIndex, phase] of roadmap.phases.entries()) {
    for (const [subIndex, sub] of phase.subPhases.entries()) {
      if (sub.status !== 'in-progress') continue;
      lines.push(`- ⏳ **${subPhaseLabel(phaseIndex, subIndex)}** ${sub.title} (\`${sub.id}\`) — in progress since ${sub.startedOn}`);
    }
  }
  const upcoming = nextCandidates(roadmap, 5);
  if (upcoming.length === 0) lines.push('Nothing else is eligible: every remaining item is blocked, deferred or waiting on a dependency.');
  for (const item of upcoming) {
    lines.push(`- **${item.label}** ${item.subPhase.title} (\`${item.subPhase.id}\`) — ${item.subPhase.scope}`);
  }
  lines.push('');

  for (const [index, phase] of roadmap.phases.entries()) {
    lines.push(...renderPhase(roadmap, phase, index));
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderPhase(roadmap: Roadmap, phase: Phase, index: number): string[] {
  const lines: string[] = [];
  const milestone = roadmap.milestones.find((m) => m.id === phase.milestone)?.title ?? phase.milestone;
  lines.push(`## ${phaseLabel(index)} — ${phase.title} <a id="phase-${phase.id}"></a>`);
  lines.push('');
  lines.push(phase.goal);
  lines.push('');
  const deps = phase.dependsOn.length > 0 ? phase.dependsOn.map((d) => `\`${d}\``).join(', ') : 'none';
  lines.push(`Id \`${phase.id}\` · Milestone: ${milestone} · Status: ${statusText(phaseStatus(phase))} · Depends on: ${deps}`);
  lines.push('');
  for (const [subIndex, sub] of phase.subPhases.entries()) {
    lines.push(...renderSubPhase(sub, subPhaseLabel(index, subIndex)));
  }
  lines.push('');
  return lines;
}

function renderSubPhase(sub: SubPhase, label: string): string[] {
  const box = sub.status === 'done' ? '[x]' : '[ ]';
  const marker = statusMarker(sub);
  const lines = [`- ${box} **${label}** ${sub.title} (\`${sub.id}\`)${marker} <a id="${sub.id}"></a>`];
  lines.push(`  ${sub.scope}`);
  for (const criterion of sub.acceptance) lines.push(`  - ${criterion}`);
  if (sub.dependsOn.length > 0) lines.push(`  - Depends on: ${sub.dependsOn.map((d) => `\`${d}\``).join(', ')}`);
  if (sub.tags.length > 0) lines.push(`  - Tags: ${sub.tags.join(', ')}`);
  if (sub.notes) lines.push(`  - Note: ${sub.notes}`);
  return lines;
}

function statusMarker(sub: SubPhase): string {
  switch (sub.status) {
    case 'done':
      return ` — done ${sub.completedOn}`;
    case 'in-progress':
      return ` — ⏳ in progress since ${sub.startedOn}`;
    case 'blocked':
      return ` — ⛔ blocked: ${sub.blockedReason}`;
    case 'deferred':
      return ' — ⏸ deferred';
    default:
      return '';
  }
}

function statusText(status: SubPhase['status']): string {
  switch (status) {
    case 'done':
      return 'done';
    case 'in-progress':
      return '⏳ in progress';
    case 'blocked':
      return '⛔ blocked';
    case 'deferred':
      return '⏸ deferred';
    default:
      return 'planned';
  }
}

function progressBar(done: number, total: number): string {
  const ratio = total === 0 ? 0 : done / total;
  const filled = Math.round(ratio * BAR_WIDTH);
  return `${'█'.repeat(filled)}${'░'.repeat(BAR_WIDTH - filled)} ${Math.round(ratio * 100)}%`;
}

export type Candidate = { label: string; subPhase: SubPhase; phase: Phase };

export function nextCandidates(roadmap: Roadmap, limit: number): Candidate[] {
  const result: Candidate[] = [];
  for (const [phaseIndex, phase] of roadmap.phases.entries()) {
    if (phase.deferred) continue;
    if (!phase.dependsOn.every((d) => isDone(roadmap, d))) continue;
    for (const [subIndex, sub] of phase.subPhases.entries()) {
      if (sub.status !== 'planned') continue;
      if (!sub.dependsOn.every((d) => isDone(roadmap, d))) continue;
      result.push({ label: subPhaseLabel(phaseIndex, subIndex), subPhase: sub, phase });
      if (result.length >= limit) return result;
    }
  }
  return result;
}
