fail-on-severity: high
fail-on-scopes:
  - runtime
  - development
  - unknown
comment-summary-in-pr: on-failure
allow-licenses:
  - 0BSD
  - Apache-2.0
  - BlueOak-1.0.0
  - BSD-2-Clause
  - BSD-3-Clause
  - CC-BY-4.0
  - CC0-1.0
  - ISC
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - MIT
  - MIT-0
  - MPL-2.0
  - OFL-1.1
  - Python-2.0
  - Unlicense
  - Zlib
allow-dependencies-licenses:
  - pkg:npm/geist
  - pkg:nuget/Microsoft.Data.SqlClient.SNI.runtime
  - pkg:nuget/Microsoft.Identity.Client.NativeInterop
  - pkg:nuget/Microsoft.Testing.Extensions.CodeCoverage
