<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Dewiride.Erp.BuildingBlocks.UnitTests" />
    <InternalsVisibleTo Include="Dewiride.Erp.Host.Api.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Endpoints/Dewiride.Erp.BuildingBlocks.Endpoints/Dewiride.Erp.BuildingBlocks.Endpoints.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Identity.Web" />
  </ItemGroup>

</Project>
