// <auto-generated />
using System;
using Dewiride.Erp.BuildingBlocks.Auditing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dewiride.Erp.BuildingBlocks.Auditing.Persistence.Migrations
{
    [DbContext(typeof(AuditingDbContext))]
    [Migration("20261010025421_InitialAuditing")]
    partial class InitialAuditing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dewiride.Erp.BuildingBlocks.Auditing.Security.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("ClientApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Detail")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ActorObjectId", "OccurredAt");

                    b.ToTable("SecurityEvents", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
