<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../../../Module/Dewiride.Erp.Modules.Platform.SystemInfo/Dewiride.Erp.Modules.Platform.SystemInfo.csproj" />
    <ProjectReference Include="../../../../../../Hosts/Api/Dewiride.Erp.Host.Api/Dewiride.Erp.Host.Api.csproj" />
    <ProjectReference Include="../../../../../../Tests/Shared/Dewiride.Erp.Testing/Dewiride.Erp.Testing.csproj" />
  </ItemGroup>

</Project>
