// <auto-generated />
using System;
using Dewiride.Erp.BuildingBlocks.Caching.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dewiride.Erp.BuildingBlocks.Caching.Persistence.Migrations
{
    [DbContext(typeof(CachingDbContext))]
    [Migration("20261002125851_InitialCaching")]
    partial class InitialCaching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform_caching")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dewiride.Erp.BuildingBlocks.Caching.Persistence.DistributedCacheEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(449)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(449)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SlidingExpirationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtTime")
                        .HasDatabaseName("Index_ExpiresAtTime");

                    b.ToTable("DistributedCacheEntries", "platform_caching");
                });
#pragma warning restore 612, 618
        }
    }
}
